[2025-01-26T22:36:33.558+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-01-26T22:36:33.598+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: excel_to_mysql_stock_capro.excel_to_mysql_stock_capro manual__2025-01-26T22:36:29.974689+00:00 [queued]>
[2025-01-26T22:36:33.613+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: excel_to_mysql_stock_capro.excel_to_mysql_stock_capro manual__2025-01-26T22:36:29.974689+00:00 [queued]>
[2025-01-26T22:36:33.615+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2025-01-26T22:36:33.644+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): excel_to_mysql_stock_capro> on 2025-01-26 22:36:29.974689+00:00
[2025-01-26T22:36:33.661+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=177) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-01-26T22:36:33.664+0000] {standard_task_runner.py:72} INFO - Started process 179 to run task
[2025-01-26T22:36:33.661+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'excel_to_mysql_stock_capro', 'excel_to_mysql_stock_capro', 'manual__2025-01-26T22:36:29.974689+00:00', '--job-id', '767', '--raw', '--subdir', 'DAGS_FOLDER/read_import_excel_file_database_mysql.py', '--cfg-path', '/tmp/tmp6fqvnonj']
[2025-01-26T22:36:33.668+0000] {standard_task_runner.py:105} INFO - Job 767: Subtask excel_to_mysql_stock_capro
[2025-01-26T22:36:34.097+0000] {task_command.py:467} INFO - Running <TaskInstance: excel_to_mysql_stock_capro.excel_to_mysql_stock_capro manual__2025-01-26T22:36:29.974689+00:00 [running]> on host 340d747f4248
[2025-01-26T22:36:34.332+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='excel_to_mysql_stock_capro' AIRFLOW_CTX_TASK_ID='excel_to_mysql_stock_capro' AIRFLOW_CTX_EXECUTION_DATE='2025-01-26T22:36:29.974689+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-01-26T22:36:29.974689+00:00'
[2025-01-26T22:36:34.337+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-01-26T22:36:34.338+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-01-26T22:36:34.339+0000] {logging_mixin.py:190} INFO - Current task name:excel_to_mysql_stock_capro state:running start_date:2025-01-26 22:36:33.599442+00:00
[2025-01-26T22:36:34.339+0000] {logging_mixin.py:190} INFO - Dag name:excel_to_mysql_stock_capro and current dag run status:running
[2025-01-26T22:36:34.340+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-01-26T22:36:34.343+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/read_import_excel_file_database_mysql.py", line 23, in process_and_import_excel
    with open(log_file, 'a') as log:
         ^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/HP/Documents/TextimportationPython/files/log.txt'
[2025-01-26T22:36:34.410+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-01-26T22:36:34.412+0000] {logging_mixin.py:190} INFO - Task start:2025-01-26 22:36:33.599442+00:00 end:2025-01-26 22:36:34.409127+00:00 duration:0.809685
[2025-01-26T22:36:34.413+0000] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): excel_to_mysql_stock_capro> dag:<DAG: excel_to_mysql_stock_capro> dagrun:<DagRun excel_to_mysql_stock_capro @ 2025-01-26 22:36:29.974689+00:00: manual__2025-01-26T22:36:29.974689+00:00, state:running, queued_at: 2025-01-26 22:36:29.995897+00:00. externally triggered: True>
[2025-01-26T22:36:34.414+0000] {logging_mixin.py:190} INFO - Failure caused by [Errno 2] No such file or directory: 'C:/Users/HP/Documents/TextimportationPython/files/log.txt'
[2025-01-26T22:36:34.415+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=excel_to_mysql_stock_capro, task_id=excel_to_mysql_stock_capro, run_id=manual__2025-01-26T22:36:29.974689+00:00, execution_date=20250126T223629, start_date=20250126T223633, end_date=20250126T223634
[2025-01-26T22:36:34.462+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-01-26T22:36:34.464+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 767 for task excel_to_mysql_stock_capro ([Errno 2] No such file or directory: 'C:/Users/HP/Documents/TextimportationPython/files/log.txt'; 179)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/read_import_excel_file_database_mysql.py", line 23, in process_and_import_excel
    with open(log_file, 'a') as log:
         ^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/HP/Documents/TextimportationPython/files/log.txt'
[2025-01-26T22:36:34.527+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-01-26T22:36:34.800+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-01-26T22:36:34.804+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
