[2025-01-27T23:28:59.300+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-01-27T23:28:59.334+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: verifier_repertoire_dag.verifier_et_log_task manual__2025-01-27T23:28:56.067099+00:00 [queued]>
[2025-01-27T23:28:59.352+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: verifier_repertoire_dag.verifier_et_log_task manual__2025-01-27T23:28:56.067099+00:00 [queued]>
[2025-01-27T23:28:59.353+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2025-01-27T23:28:59.384+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): verifier_et_log_task> on 2025-01-27 23:28:56.067099+00:00
[2025-01-27T23:28:59.396+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=152) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-01-27T23:28:59.400+0000] {standard_task_runner.py:72} INFO - Started process 161 to run task
[2025-01-27T23:28:59.401+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'verifier_repertoire_dag', 'verifier_et_log_task', 'manual__2025-01-27T23:28:56.067099+00:00', '--job-id', '918', '--raw', '--subdir', 'DAGS_FOLDER/mydag_check_directory.py', '--cfg-path', '/tmp/tmpuhyph8uo']
[2025-01-27T23:28:59.403+0000] {standard_task_runner.py:105} INFO - Job 918: Subtask verifier_et_log_task
[2025-01-27T23:29:00.248+0000] {task_command.py:467} INFO - Running <TaskInstance: verifier_repertoire_dag.verifier_et_log_task manual__2025-01-27T23:28:56.067099+00:00 [running]> on host 340d747f4248
[2025-01-27T23:29:00.414+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='verifier_repertoire_dag' AIRFLOW_CTX_TASK_ID='verifier_et_log_task' AIRFLOW_CTX_EXECUTION_DATE='2025-01-27T23:28:56.067099+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-01-27T23:28:56.067099+00:00'
[2025-01-27T23:29:00.416+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-01-27T23:29:00.417+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-01-27T23:29:00.418+0000] {logging_mixin.py:190} INFO - Current task name:verifier_et_log_task state:running start_date:2025-01-27 23:28:59.336032+00:00
[2025-01-27T23:29:00.418+0000] {logging_mixin.py:190} INFO - Dag name:verifier_repertoire_dag and current dag run status:running
[2025-01-27T23:29:00.419+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-01-27T23:29:00.420+0000] {logging_mixin.py:190} INFO - [INFO] 2025-01-27 23:29:00.420544 - Vérification du répertoire : /opt/***/files
[2025-01-27T23:29:00.421+0000] {logging_mixin.py:190} INFO - jhjhjhjh [ERREUR] 2025-01-27 23:29:00.421178 - Le répertoire '/opt/***/files' n'existe pas.
[2025-01-27T23:29:00.421+0000] {python.py:240} INFO - Done. Returned value was: False
[2025-01-27T23:29:00.465+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-01-27T23:29:00.466+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=verifier_repertoire_dag, task_id=verifier_et_log_task, run_id=manual__2025-01-27T23:28:56.067099+00:00, execution_date=20250127T232856, start_date=20250127T232859, end_date=20250127T232900
[2025-01-27T23:29:00.485+0000] {logging_mixin.py:190} INFO - Task instance in success state
[2025-01-27T23:29:00.490+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: running
[2025-01-27T23:29:00.493+0000] {logging_mixin.py:190} INFO - Dag name:verifier_repertoire_dag queued_at:2025-01-27 23:28:56.082250+00:00
[2025-01-27T23:29:00.494+0000] {logging_mixin.py:190} INFO - Task hostname:340d747f4248 operator:PythonOperator
[2025-01-27T23:29:00.529+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-01-27T23:29:00.832+0000] {taskinstance.py:3895} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-01-27T23:29:00.835+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
