[2025-01-26T22:51:07.651+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-01-26T22:51:07.674+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: excel_to_mysql_stock_capro.excel_to_mysql_stock_capro manual__2025-01-26T22:51:04.024828+00:00 [queued]>
[2025-01-26T22:51:07.685+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: excel_to_mysql_stock_capro.excel_to_mysql_stock_capro manual__2025-01-26T22:51:04.024828+00:00 [queued]>
[2025-01-26T22:51:07.687+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2025-01-26T22:51:07.727+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): excel_to_mysql_stock_capro> on 2025-01-26 22:51:04.024828+00:00
[2025-01-26T22:51:07.740+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=377) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-01-26T22:51:07.743+0000] {standard_task_runner.py:72} INFO - Started process 379 to run task
[2025-01-26T22:51:07.744+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'excel_to_mysql_stock_capro', 'excel_to_mysql_stock_capro', 'manual__2025-01-26T22:51:04.024828+00:00', '--job-id', '773', '--raw', '--subdir', 'DAGS_FOLDER/read_import_excel_file_database_mysql.py', '--cfg-path', '/tmp/tmp9ed5jxlu']
[2025-01-26T22:51:07.748+0000] {standard_task_runner.py:105} INFO - Job 773: Subtask excel_to_mysql_stock_capro
[2025-01-26T22:51:08.148+0000] {task_command.py:467} INFO - Running <TaskInstance: excel_to_mysql_stock_capro.excel_to_mysql_stock_capro manual__2025-01-26T22:51:04.024828+00:00 [running]> on host 340d747f4248
[2025-01-26T22:51:08.283+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='excel_to_mysql_stock_capro' AIRFLOW_CTX_TASK_ID='excel_to_mysql_stock_capro' AIRFLOW_CTX_EXECUTION_DATE='2025-01-26T22:51:04.024828+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-01-26T22:51:04.024828+00:00'
[2025-01-26T22:51:08.285+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-01-26T22:51:08.286+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-01-26T22:51:08.287+0000] {logging_mixin.py:190} INFO - Current task name:excel_to_mysql_stock_capro state:running start_date:2025-01-26 22:51:07.675780+00:00
[2025-01-26T22:51:08.288+0000] {logging_mixin.py:190} INFO - Dag name:excel_to_mysql_stock_capro and current dag run status:running
[2025-01-26T22:51:08.288+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-01-26T22:51:08.290+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/read_import_excel_file_database_mysql.py", line 25, in process_and_import_excel
    print('borisss',log.read())
                    ^^^^^^^^^^
io.UnsupportedOperation: not readable
[2025-01-26T22:51:08.318+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-01-26T22:51:08.321+0000] {logging_mixin.py:190} INFO - Task start:2025-01-26 22:51:07.675780+00:00 end:2025-01-26 22:51:08.317609+00:00 duration:0.641829
[2025-01-26T22:51:08.330+0000] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): excel_to_mysql_stock_capro> dag:<DAG: excel_to_mysql_stock_capro> dagrun:<DagRun excel_to_mysql_stock_capro @ 2025-01-26 22:51:04.024828+00:00: manual__2025-01-26T22:51:04.024828+00:00, state:running, queued_at: 2025-01-26 22:51:04.148079+00:00. externally triggered: True>
[2025-01-26T22:51:08.331+0000] {logging_mixin.py:190} INFO - Failure caused by not readable
[2025-01-26T22:51:08.332+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=excel_to_mysql_stock_capro, task_id=excel_to_mysql_stock_capro, run_id=manual__2025-01-26T22:51:04.024828+00:00, execution_date=20250126T225104, start_date=20250126T225107, end_date=20250126T225108
[2025-01-26T22:51:08.360+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-01-26T22:51:08.362+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 773 for task excel_to_mysql_stock_capro (not readable; 379)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/read_import_excel_file_database_mysql.py", line 25, in process_and_import_excel
    print('borisss',log.read())
                    ^^^^^^^^^^
io.UnsupportedOperation: not readable
[2025-01-26T22:51:08.404+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-01-26T22:51:08.627+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-01-26T22:51:08.639+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
