[2025-01-28T20:14:18.736+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-01-28T20:14:18.778+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: verifier_repertoire_dag.verifier_et_log_task2 manual__2025-01-28T20:14:11.637269+00:00 [queued]>
[2025-01-28T20:14:18.794+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: verifier_repertoire_dag.verifier_et_log_task2 manual__2025-01-28T20:14:11.637269+00:00 [queued]>
[2025-01-28T20:14:18.795+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2025-01-28T20:14:18.819+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): verifier_et_log_task2> on 2025-01-28 20:14:11.637269+00:00
[2025-01-28T20:14:18.836+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=169) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-01-28T20:14:18.848+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'verifier_repertoire_dag', 'verifier_et_log_task2', 'manual__2025-01-28T20:14:11.637269+00:00', '--job-id', '935', '--raw', '--subdir', 'DAGS_FOLDER/mydag_check_directory.py', '--cfg-path', '/tmp/tmpel55lgv2']
[2025-01-28T20:14:18.849+0000] {standard_task_runner.py:72} INFO - Started process 171 to run task
[2025-01-28T20:14:18.850+0000] {standard_task_runner.py:105} INFO - Job 935: Subtask verifier_et_log_task2
[2025-01-28T20:14:19.495+0000] {task_command.py:467} INFO - Running <TaskInstance: verifier_repertoire_dag.verifier_et_log_task2 manual__2025-01-28T20:14:11.637269+00:00 [running]> on host 340d747f4248
[2025-01-28T20:14:19.642+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='verifier_repertoire_dag' AIRFLOW_CTX_TASK_ID='verifier_et_log_task2' AIRFLOW_CTX_EXECUTION_DATE='2025-01-28T20:14:11.637269+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-01-28T20:14:11.637269+00:00'
[2025-01-28T20:14:19.645+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-01-28T20:14:19.646+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-01-28T20:14:19.646+0000] {logging_mixin.py:190} INFO - Current task name:verifier_et_log_task2 state:running start_date:2025-01-28 20:14:18.779446+00:00
[2025-01-28T20:14:19.647+0000] {logging_mixin.py:190} INFO - Dag name:verifier_repertoire_dag and current dag run status:running
[2025-01-28T20:14:19.648+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-01-28T20:14:19.649+0000] {logging_mixin.py:190} INFO - Le r√©pertoire n'existe pas : /opt/***/files
[2025-01-28T20:14:19.650+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-01-28T20:14:19.667+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-01-28T20:14:19.669+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=verifier_repertoire_dag, task_id=verifier_et_log_task2, run_id=manual__2025-01-28T20:14:11.637269+00:00, execution_date=20250128T201411, start_date=20250128T201418, end_date=20250128T201419
[2025-01-28T20:14:19.687+0000] {logging_mixin.py:190} INFO - Task instance in success state
[2025-01-28T20:14:19.688+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: running
[2025-01-28T20:14:19.692+0000] {logging_mixin.py:190} INFO - Dag name:verifier_repertoire_dag queued_at:2025-01-28 20:14:11.681144+00:00
[2025-01-28T20:14:19.693+0000] {logging_mixin.py:190} INFO - Task hostname:340d747f4248 operator:PythonOperator
[2025-01-28T20:14:19.759+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-01-28T20:14:20.007+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-01-28T20:14:20.011+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
